openapi: 3.0.1
info:
  title: LoccanaAccountingReceiveReport
  description: API Definition of LoccanaAccountingReceiveReport
  version: 1.0.0
servers:
- url: http://localhost:8290/accounting
paths:
  /:
    post:
      responses:
        default:
          description: Default response
