openapi: 3.0.1
info:
  title: LoccanaAccountingFinanceReport
  description: API Definition of LoccanaAccountingFinanceReport
  version: 1.0.0
servers:
- url: http://localhost:8290/accounting/financereport
paths:
  /lists:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
